package PerlDocJp::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'PerlDocJp::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:perldocjp',
        user => 'root',
        password => 'mymymy',
    }
);

=head1 NAME

PerlDocJp::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PerlDocJp>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PerlDocJp::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.29

=head1 AUTHOR



=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
